### ISSUE TITLE
Generalise the op_solver to work with aribtrary start and end points

### ISSUE THREAD

**Issue by lounick** [lounick/task_scheduling#2]
The current state of the orienteering problem solver assumes that the first point (0) in the cost matrix is the starting point and that the last (n-1) is the finishing point.

It should be generalised to be working with any point. Even with the case of the starting and ending point being the same.

**Comment by decabyte** [comment]
:+1: for this one

**Comment by lounick** [comment]
Fixed in https://github.com/lounick/task_scheduling/commit/be4208a2577d6d6ebf7bd14f0b4ea484fefdf31b
